// Candidate F&B chain names to verify against the ICP (5+ outlets, any Indian city).
// Public knowledge of real chains, grouped by how likely they already sit on a mature
// SDR's radar — used to order discovery so obvious national names are tried (and usually
// excluded) first, saving quota for the regional/mid-size names more likely to be new leads.

export const NATIONAL_CANDIDATES = [
  "Behrouz Biryani",
  "Wow! Momo",
  "Chai Point",
  "Third Wave Coffee",
  "Sagar Ratna",
  "Mainland China",
  "Truffles",
  "Faasos",
  "Haldiram's",
  "Bikanervala",
  "Barbeque Nation",
  "Absolute Barbecues",
  "Mad Over Donuts",
  "Ovenstory Pizza",
  "Box8",
  "Rolls Kingdom",
  "Sarvana Bhavan",
  "Anjappar",
  "Kim Lee",
  "Chinita",
];

export const REGIONAL_CANDIDATES = [
  "Slay Coffee",
  "Blue Tokai Coffee Roasters",
  "The Beer Cafe",
  "Naturals Ice Cream",
  "Keventers",
  "La Pino'z Pizza",
  "Nathu's Sweets",
  "Prakash Sweets",
  "Kanha Sweets",
  "Meghana Foods",
  "Empire Restaurant",
  "Vidyarthi Bhavan",
  "Nirula's",
  "Kailash Parbat",
  "Karim's",
  "Paradise Biryani",
  "Shah Ghouse",
  "Cream Centre",
  "Rajdhani Thali",
  "Swati Snacks",
  "A2B Adyar Ananda Bhavan",
  "Murugan Idli Shop",
  "Only Parathas",
  "Chef Kylin",
  "Punjab Grill",
  "Yo! China",
  "Copper Chimney",
  "Moti Mahal",
  "Bercos",
  "Ministry of Beer",
  "Social Offline",
  "Smoke House Deli",
  "Yauatcha",
  "Farzi Cafe",
  "Big Chill",
  "Theobroma",
  "Monginis",
  "Karachi Bakery",
  "Iyer's Bakery",
  "Sweet Bengal",
];

export const ALL_CANDIDATES = [...NATIONAL_CANDIDATES, ...REGIONAL_CANDIDATES];
